# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

- powershell: |
    Write-Host "Using a global non-secret var mapped in the pipeline works: $env:NUGETAPIKEY.Substring(0, 5)" 
    Write-Host "Using the mapped env var for this task works and is recommended: $env:NUGETAPIKEY.Length"
    Write-Host "My secret $(nugetApiKey)"
  env:
    NUGETAPIKEY: $(nugetApiKey2)

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Main(0f20fa13-72d9-4772-87e4-6646d8ac0663)'
    workingDirectory: '$(Build.SourcesDirectory)\PSAvroTools\'
    ScriptType: 'FilePath'
    ScriptPath: 'PSAvroTools\publish.ps1'
    azurePowerShellVersion: 'LatestVersion'
  env:
    NUGETAPIKEY: ${nugetApiKey}
