# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish -c Release /p:DebugType=None /p:DebugSymbols=false
    - name: Create Publish Folder
      shell: pwsh
      run: New-Item -Path './PSAvroTools/bin/Release/netstandard2.0/publish/AvroTools/' -ItemType Directory -Force
    - name: Copy from release folder to publish folder
      shell: pwsh
      run: copy ./PSAvroTools/bin/Release/netstandard2.0/publish/*.* ./PSAvroTools/bin/Release/netstandard2.0/publish/AvroTools/
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Integration Tests
      shell: pwsh
      run: Invoke-Pester ./PSAvroTools/IntegrationTests/ -PassThru
    - name: Publish to Powershell gallery
      shell: pwsh
      env:
        NUGETAPIKEY: ${{ secrets.NugetApiKey }}
      run: ./PSAvroTools/publish.ps1
